sudo: required

services:
- docker

arch:
    packages:
    - go-pie
    - dep
    - go-tools
    - procps-ng
    script:
    - unset GOROOT
    - export GOPATH=$HOME/go
    - mkdir -p $GOPATH/src
    - ln -rTsf $PWD $GOPATH/src/radiucal
    - cd $GOPATH/src/radiucal
    - dep ensure
    - make

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

notifications:
    email:
        on_success: change
        on_failure: change
